new cookbook: Creating Subtitles with Speaker Labels
AssemblyAI/cookbook pull request #23
Opened 2023-12-22 15:39 UTC by m-ods

2023-12-22 22:20 UTC, MLawlz requested changes

2023-12-22 22:20 UTC, MLawlz commented on core-transcription/speaker_labelled_subtitles.ipynb
> +        "def format_time(milliseconds):\n",
I found an interesting thread on using `divmod` that might simplify this code a bit: https://stackoverflow.com/questions/72975483/milliseconds-to-hhmmss-time-format

2023-12-22 22:20 UTC, MLawlz commented on core-transcription/speaker_labelled_subtitles.ipynb
> +        "with open(filename + '.srt', 'w') as file:\n",
Just as a best practice, it might be best to include a quick call to `file.close()` after this `with` statement.

2023-12-24 07:29 UTC, m-ods commented on core-transcription/speaker_labelled_subtitles.ipynb
> +        "with open(filename + '.srt', 'w') as file:\n",
The with statement in Python is actually a context manager for file handling, which ensures that the file is properly closed after its suite finishes, even if an exception is raised. This means that the file.close() method is implicitly called at the end of the with block.

2023-12-26 00:51 UTC, MLawlz commented on core-transcription/speaker_labelled_subtitles.ipynb
> +        "with open(filename + '.srt', 'w') as file:\n",
Nice! Didn't know that 💡

2023-12-26 00:52 UTC, MLawlz approved these changes
Looks great!

2023-12-26 00:52 UTC, merged